//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ass3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Student
    {
        public int Id { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string Firstname { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string Lastname { get; set; }

        [Required]
        [RegularExpression("04[0-9]{8}",ErrorMessage="Invalid mobile number")]
        public string Mobile { get; set; }

        [Required]
        public Nullable<int> Course { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string Address { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string State { get; set; }

        [Required]
        [RegularExpression("[0-9]{4}",ErrorMessage="Invalid postcode")]
        public string Postcode { get; set; }

        [Required]
        [DisplayFormat(DataFormatString="{0:dd/MM/yyyy}",ApplyFormatInEditMode=true)]
        public Nullable<System.DateTime> DateOfBirth { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        public string E_mail { get; set; }

        public virtual Course Course1 { get; set; }
    }
}
